name: Keep Render Awake

on:
  schedule:
    # Every 10 minutes
    - cron: "*/14 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Render Server
        run: |
          curl -L https://zms-lizza-backend.onrender.com/api/v1/health